import { useRef, useState, type FormEvent, type PointerEvent } from 'react'
import { ArrowRight, Check, Heart, LockKeyhole, Mic, Pencil, Plus, Save, Sparkles, Undo2, X } from 'lucide-react'
import { createPost, errorText, type Nook } from './lib'
import { GamePanel, Modal, type Action } from './Base'
import { AudioPlayer, AudioRecorder } from './Media'
import { LetterShelf } from './Letters'
import { dateInZone, feedback } from './interactions'
import type { Prompt, Shared, Stroke } from './useShared'

function QuestionCard({prompt,nook,shared,act,busy}:{prompt:Prompt;nook:Nook;shared:Shared;act:Action;busy:boolean}) {
  const own=prompt.answers.find(a=>a.user_id===nook.profile.id)
  const [answer,setAnswer]=useState(own?.answer||'')
  const [editing,setEditing]=useState(false)
  const both=prompt.answered_by.length>=2
  const partner=nook.people.find(p=>p.id!==nook.profile.id)
  const sound=nook.posts.find(p=>p.id===prompt.audio_post_id)
  const sealed=Boolean(own)&&!both&&!editing
  const guessHost=prompt.kind==='guess'&&prompt.author_id===nook.profile.id
  async function send(e:FormEvent){e.preventDefault();if(await act(()=>shared.call('answer',{p_id:prompt.id,p_answer:answer.trim()}),'Your answer is tucked safely inside.'))setEditing(false)}
  return <article className={`question-card ${both?'revealed':''}`}><div className="question-top"><span className="eyebrow">{prompt.kind==='daily'?'TODAY, BETWEEN US':prompt.kind==='either'?'WOULD YOU RATHER':prompt.kind==='guess'?'GUESS MY LITTLE SOUND':'A QUESTION FOR TWO'}</span>{both?<Check/>:<Sparkles/>}</div>
    <h2>“{prompt.prompt}”</h2>
    {prompt.kind==='guess'&&(sound?<AudioPlayer post={sound} compact/>:<p className="muted">This recording is no longer in the current collection.</p>)}
    {both?<div className="revealed-answers">{nook.people.map(person=>{const response=prompt.answers.find(a=>a.user_id===person.id);return <div className="answer-letter" key={person.id}><span>{person.avatar} {person.display_name}</span><p>{response?.answer||'An answer, kept between you.'}</p></div>})}<div className="reveal-caption"><Heart/>Two little windows into each other.</div></div>:<>
      <div className="answer-status"><span><i className={own?'answered':''}/>{own?'Your words are sealed':'Your words, when you are ready'}</span><span><i className={prompt.answered_by.includes(partner?.id||'')?'answered':''}/>{partner?.display_name||'Your person'} {prompt.answered_by.includes(partner?.id||'')?'has answered':'has not answered yet'}</span></div>
      {sealed?<div className="sealed-answer"><LockKeyhole/><p>{guessHost?'The answer is safe. Waiting for their guess.':'Your words are tucked inside. Both answers open after your person replies.'}</p><button className="text-button" disabled={busy} onClick={()=>{setAnswer(own?.answer||'');setEditing(true)}}>Amend my answer <Pencil/></button></div>:<form onSubmit={send} className="answer-form">{prompt.kind==='either'?<fieldset><legend className="sr-only">Your choice</legend><div className="choice-cards">{prompt.options?.map(option=><label key={option} className={answer===option?'selected':''}><input type="radio" name={prompt.id} value={option} checked={answer===option} onChange={()=>setAnswer(option)} required/><Heart/><span>{option}</span></label>)}</div></fieldset>:<label><span className="sr-only">Your answer</span><textarea rows={3} value={answer} maxLength={4000} required onChange={e=>setAnswer(e.target.value)} placeholder={prompt.kind==='guess'?'Is that the rain on your window?':'Something only you would say…'}/></label>}<button className="button" disabled={busy||!answer.trim()}><LockKeyhole/>{prompt.kind==='guess'?'Send my guess':'Seal my answer'}</button></form>}
    </>}
  </article>
}

function NewQuestion({kind,nook,shared,act,busy,close}:{kind:'question'|'either'|'guess';nook:Nook;shared:Shared;act:Action;busy:boolean;close:()=>void}) {
  const [prompt,setPrompt]=useState(kind==='guess'?'What can you hear from my little corner?':''),[a,setA]=useState(''),[b,setB]=useState(''),[answer,setAnswer]=useState(''),[clip,setClip]=useState(''),[file,setFile]=useState<File>(),[error,setError]=useState('')
  const [recording,setRecording]=useState(false)
  async function submit(e:FormEvent){e.preventDefault();if(recording)return;setError('');if(kind==='guess'&&!clip&&!file){setError('Choose or record a sound first.');return}
    if(await act(async()=>{let audio=clip;if(file&&!audio){audio=await createPost(nook,'voice','',null,file,{title:'Guess this little sound'});setClip(audio)}await shared.call('create_prompt',{p_kind:kind,p_prompt:prompt.trim(),p_options:kind==='either'?[a.trim(),b.trim()]:null,p_audio:kind==='guess'?audio:null,p_answer:kind==='guess'?answer.trim():null})},'A new little conversation is waiting.',setError))close()
  }
  return <Modal title={kind==='either'?'Two choices. Two of you.':kind==='guess'?'Whisper roulette':'Ask something just for you two'} busy={busy} close={close}><form className="stack-form" onSubmit={submit}><label>Your question<textarea rows={3} required maxLength={500} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="If we had one impossible hour together…"/></label>{kind==='either'&&<div className="form-columns"><label>One possibility<input required maxLength={120} value={a} onChange={e=>setA(e.target.value)}/></label><label>Or this one<input required maxLength={120} value={b} onChange={e=>setB(e.target.value)}/></label></div>}{kind==='guess'&&<><AudioRecorder onActivity={setRecording} onReady={f=>{setFile(f);setClip('')}}/>{file&&<p className="form-message">Your new recording is ready.</p>}<label>Or use one of your recordings<select value={clip} onChange={e=>{setClip(e.target.value);setFile(undefined)}}><option value="">Choose a recording</option>{nook.posts.filter(p=>p.author_id===nook.profile.id&&['voice','ambient'].includes(p.kind)).map(p=><option key={p.id} value={p.id}>{p.metadata?.title||'A little recording'}</option>)}</select></label><label>The answer <span>(hidden until they guess)</span><input required maxLength={120} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Rain against the kitchen window"/></label></>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button" disabled={busy||recording}><Heart/>Leave it for us</button></form></Modal>
}

const strokeColors={rose:'#804650',sage:'#6f795f',lilac:'#897094',ink:'#463338'}
export function DoodleBoard({nook,shared,act,busy}:{nook:Nook;shared:Shared;act:Action;busy:boolean}) {
  const [color,setColor]=useState<Stroke['color']>('rose'),[draft,setDraft]=useState<[number,number][]>([]),[pending,setPending]=useState<Stroke[]>([]),[error,setError]=useState(''),[caption,setCaption]=useState(''),[clear,setClear]=useState(false),[cursor,setCursor]=useState<[number,number]>([500,350])
  const current=useRef<[number,number][]>([]),paper=useRef<SVGSVGElement>(null),queue=useRef(Promise.resolve()),keyDrawing=useRef(false)
  const all=[...shared.data.strokes,...pending]
  function position(e:PointerEvent<SVGSVGElement>):[number,number]{const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1000,(e.clientX-r.left)*1000/r.width)),Math.max(0,Math.min(700,(e.clientY-r.top)*700/r.height))]}
  function add(point:[number,number]){if(current.current.length>=240){current.current=current.current.filter((_,i)=>i%2===0)}current.current.push(point);setDraft([...current.current]);setCursor(point)}
  function saveStroke(points:[number,number][],selected=color){if(!points.length)return;const id=crypto.randomUUID();const stroke:Stroke={id,author_id:nook.profile.id,points,color:selected,width:7,created_at:new Date().toISOString()};setPending(p=>[...p,stroke]);queue.current=queue.current.then(async()=>{try{await shared.call('stroke',{p_points:points,p_color:selected,p_width:7});setError('')}catch(e){setError(errorText(e))}finally{setPending(p=>p.filter(s=>s.id!==id))}})}
  function finish(){if(!current.current.length)return;const points=[...current.current];current.current=[];setDraft([]);saveStroke(points);keyDrawing.current=false}
  function heart(){const points:[number,number][]=[];for(let i=0;i<=80;i++){const t=i/80*2*Math.PI;points.push([500+12*(16*Math.pow(Math.sin(t),3)),350-12*(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))])}saveStroke(points);feedback('kiss')}
  async function keep(){await act(async()=>{
    const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=700
    const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Your browser could not save this drawing.')
    ctx.fillStyle='#fffdf9';ctx.fillRect(0,0,1000,700);ctx.lineCap='round';ctx.lineJoin='round'
    for(const s of all){ctx.strokeStyle=strokeColors[s.color];ctx.lineWidth=s.width;ctx.beginPath();s.points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));if(s.points.length===1)ctx.lineTo(s.points[0][0]+.1,s.points[0][1]);ctx.stroke()}
    const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not save the drawing.')),'image/png'))
    await createPost(nook,'doodle',caption.trim(),null,new File([blob],'our-little-doodle.png',{type:'image/png'}),{title:'A little drawing from us'})
  },'Your little drawing is in the scrapbook.')}
  return <section className="doodle-panel panel"><div className="section-heading"><div><p className="eyebrow">OUR LITTLE DRAWING PAPER</p><h2>A line from me. A line from you.</h2></div><span className="tiny-tag"><Pencil/>Shared paper</span></div><div className="doodle-tools"><fieldset className="ink-picker"><legend className="sr-only">Drawing ink</legend>{(Object.keys(strokeColors) as Stroke['color'][]).map(c=><button type="button" key={c} aria-label={`${c} ink`} aria-pressed={color===c} style={{background:strokeColors[c]}} onClick={()=>setColor(c)}/>)}</fieldset><button className="text-button" onClick={heart} disabled={shared.loading||pending.length>0}><Heart/>Add a heart</button><button className="icon-button" aria-label="Undo my last stroke" disabled={busy||pending.length>0||!shared.data.strokes.some(s=>s.author_id===nook.profile.id)} onClick={()=>void act(()=>shared.call('erase_strokes',{p_all:false}))}><Undo2/></button><button className="icon-button" aria-label="Clear our drawing" disabled={busy||!all.length||pending.length>0} onClick={()=>setClear(true)}><X/></button></div>
    <svg ref={paper} className="doodle-paper" viewBox="0 0 1000 700" tabIndex={0} role="application" aria-label="Shared drawing paper" aria-describedby="drawing-help" onPointerDown={e=>{if(e.button!==0||shared.loading)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);current.current=[];add(position(e))}} onPointerMove={e=>{if(current.current.length&&e.currentTarget.hasPointerCapture(e.pointerId))add(position(e))}} onPointerUp={finish} onPointerCancel={()=>{current.current=[];setDraft([])}} onLostPointerCapture={finish} onKeyDown={e=>{if(e.key===' '){e.preventDefault();if(keyDrawing.current)finish();else{keyDrawing.current=true;current.current=[];add(cursor)}}else if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const point:[number,number]=[Math.max(0,Math.min(1000,cursor[0]+(e.key==='ArrowLeft'?-12:e.key==='ArrowRight'?12:0))),Math.max(0,Math.min(700,cursor[1]+(e.key==='ArrowUp'?-12:e.key==='ArrowDown'?12:0)))];setCursor(point);if(keyDrawing.current)add(point)}else if(e.key==='Escape'){current.current=[];setDraft([]);keyDrawing.current=false}}} onBlur={()=>{if(keyDrawing.current)finish()}}>
      <defs><pattern id="paper-dots" x="0" y="0" width="32" height="32" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#eadfd8"/></pattern></defs><rect width="1000" height="700" fill="url(#paper-dots)"/>
      {all.map(s=><polyline key={s.id} points={(s.points.length===1?[s.points[0],[s.points[0][0]+.1,s.points[0][1]]]:s.points).map(p=>p.join(',')).join(' ')} fill="none" stroke={strokeColors[s.color]} strokeWidth={s.width} strokeLinecap="round" strokeLinejoin="round"/>)}
      {draft.length>0&&<polyline points={draft.map(p=>p.join(',')).join(' ')} fill="none" stroke={strokeColors[color]} strokeWidth="7" strokeLinecap="round" strokeLinejoin="round"/>}
      <circle className="doodle-cursor" cx={cursor[0]} cy={cursor[1]} r="8" stroke={strokeColors[color]} fill="none"/>
      {!all.length&&!draft.length&&<text x="500" y="365" textAnchor="middle" fill="#78646a" fontFamily="Georgia,serif" fontSize="30" fontStyle="italic">Leave a little mark on my day.</text>}
    </svg><p id="drawing-help" className="footnote">Draw with a finger or mouse. With the keyboard: arrows move, Space lowers or lifts your pen. A stroke arrives when you lift your pen.</p>{error&&<p role="alert" className="form-error">{error}</p>}<label className="doodle-caption">A caption for our scrapbook<input maxLength={400} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Your Earl Grey is getting cold…"/></label><button className="button" disabled={busy||pending.length>0||!all.length} onClick={()=>void keep()}><Save/>{pending.length?'Saving our lines…':'Keep in our scrapbook'}</button>
    {clear&&<Modal title="A fresh piece of paper?" close={()=>setClear(false)} busy={busy}><p>This clears both of your drawings from the shared paper. Anything already saved in your scrapbook stays there.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setClear(false)}>Keep drawing</button><button className="button" disabled={busy} onClick={async()=>{if(await act(()=>shared.call('erase_strokes',{p_all:true})))setClear(false)}}>Clear our paper</button></div></Modal>}
  </section>
}

export function Parlour({nook,shared,act,busy,initialTab='questions'}:{nook:Nook;shared:Shared;act:Action;busy:boolean;initialTab?:string}) {
  const [tab,setTab]=useState(initialTab),[create,setCreate]=useState<'question'|'either'|'guess'|null>(null),[limit,setLimit]=useState(8)
  const daily=shared.data.prompts.find(p=>p.id===shared.data.daily_id)
  const questions=shared.data.prompts.filter(p=>p.id!==daily?.id&&['daily','question'].includes(p.kind))
  const games=shared.data.prompts.filter(p=>['either','guess'].includes(p.kind))
  return <><div className="page-tabs" aria-label="Parlour activities">{[['questions','A question for us'],['games','Little games'],['doodle','Doodle together'],['surprises','Surprises']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='questions'&&<><div className="parlour-intro"><span className="mini-wax"><Heart/></span><p>A little curiosity. A little honesty.<br/><em>Something new to know about you.</em></p><button className="button secondary" onClick={()=>setCreate('question')}><Plus/>Ask our own question</button></div>{daily?<QuestionCard key={daily.id} prompt={daily} nook={nook} shared={shared} act={act} busy={busy}/>:<p className="muted">Your shared question is finding its way here.</p>}{questions.length>0&&<div className="question-history"><h2>Our little conversations</h2>{questions.slice(0,limit).map(p=><details key={p.id}><summary><span>{p.prompt}<small>{p.answered_by.length===2?'Both answered':'A little reply is waiting'} · {dateInZone(p.created_at,nook.profile.timezone)}</small></span><ArrowRight/></summary><QuestionCard prompt={p} nook={nook} shared={shared} act={act} busy={busy}/></details>)}{questions.length>limit&&<button className="text-button" onClick={()=>setLimit(n=>n+8)}>More conversations <ArrowRight/></button>}</div>}</>}
    {tab==='games'&&<><div className="game-invitations"><button onClick={()=>setCreate('either')}><span><Heart/></span><h3>Would you rather?</h3><p>Two possibilities. Discover what you both choose.</p><ArrowRight/></button><button onClick={()=>setCreate('guess')}><span><Mic/></span><h3>Whisper roulette</h3><p>A tiny sound from your day. Can they guess it?</p><ArrowRight/></button></div><GamePanel nook={nook} act={act} busy={busy}/>{games.map(p=><QuestionCard key={p.id} prompt={p} nook={nook} shared={shared} act={act} busy={busy}/>)}</>}
    {tab==='doodle'&&<DoodleBoard nook={nook} shared={shared} act={act} busy={busy}/>}
    {tab==='surprises'&&<LetterShelf nook={nook} shared={shared} act={act} busy={busy} surprises/>}
    {create&&<NewQuestion kind={create} nook={nook} shared={shared} act={act} busy={busy} close={()=>setCreate(null)}/>}
  </>
}
